### PR TITLE
gitignore: Adds ignore for the binary blobs

### PR DESCRIPTION
**Pull request by frznlogic**
Signed-off-by: Oscar Andreasson <oscar.andreasson@pelagicore.com>

### CODE REVIEW

**Comment by frznlogic** [comment]
@slawr could you take a look at this one?

**Comment by slawr** [comment]
Thanks for the contribution Oscar.

The current Genivi Yocto BSP is based on the upstream YBSP v2.19. At the end of this month it will be updated to v2.23 and I see actually the Yocto part is now [posted](https://github.com/renesas-rcar/meta-renesas/releases/tag/Renesas-Yocto-v2.23.0). v2.23 contains commit [bc0a9](https://github.com/renesas-rcar/meta-renesas/commit/bc0a99ebfbe6c14c7f94b298ca89ea5e02656e78) which functionally seems equivalent to your PR. I will be updating the Pyro release I made to use v2.23 so the functionality will soon change for Pyro/Genivi 13 and therefore GDP-13. For Genivi 13 at least I would favour the upstream, although personally I prefer the fact you have been specific about the gfx tar ball names.

I see though you made this against the Genivi 12 branch though. Sorry it may seem like a stupid question, but was your need really against Genivi 12? Maybe you were using it for the flatpak work?

For Genivi 10, 11, 12 the Genivi YBSP git rep is slawr/renesas-rcar-gen3.
For Genivi 13 and beyond I am separating Yocto version and Genivi support into separate layers: 
- [slawr/meta-renesas](https://github.com/slawr/meta-renesas) YBSP providing "pure" Yocto version support
- meta-ivi-renesas layer providing Genivi Yocto Baseline specific modifications.

Speaking personally I have thought about a .gitignore in the past. I didn't add one as some might use git to version control the binary blobs. That said, I don't think it is black and white as to right or wrong, just a decision. The fact they have absorbed it upstream suggests there was sufficient demand and of course a dev can remove it if they wish. So I'm open to adding one to Genivi 12 support as well. Personally I prefer listing the tar balls individually. More maintenance but less possibility of unwanted side effect.

**Comment by frznlogic** [comment]
Hi, 

1. The genivi-12 branch, sorry, but that's the branch that was used from genivi-dev-platform when I was looking around and I figured I'd add it there to begin with. Would you prefer it on master or some other branch instead?

2. The .gitignore, I see your point that others might want to version control this in their own forks, but I'm not sure I think that's a reason to not have a .gitignore for it. They could always remove the .gitignore for those files in their fork in that case.

As it stands, when you use renesas-rcar-gen3 repo in a yocto setup like the genivi-dev-platform, I always wind up with a "modified" repository and then I need to doublecheck that I don't have any real changes in the repo that needs to be dealt with. It's not a huge problem I know, and could probably be solved with a better memory, but I'd really like to keep out those unnecessary modified markers when possible :-) . 

If you feel that this is not worth adding, please close it :)

**Comment by slawr** [comment]
This is one of those conversations that would be done in 10 mins f2f over a coffee, but takes longer in a thread :) so thanks for taking the time to explain further.

I hadn't considered the GDP case you give. I guess its natural for me to be checking anyway if I'm updating the YBSP :) It's a good point that would of course apply to more than just GDP and bolsters the case for adding a gitignore. As I said I'm not strongly against it and I think I will make the change for Genivi 12.

I was thinking last night that as much as I might go the route of listing all the mmp files out in the .gitignore, I think your fix is an improvement over the more blanket approach in the upstream.

For Pyro/Genivi 13 I will take the upstream when I update to YBSP v2.23. That will be done soon. It's cleaner to take that and improve the upstream if necessary, rather than endlessly carrying a downstream patch.

For Genivi 12 I'm minded to take yours as a first step as you have tested it, but either way I'll add a gitgnore.

Fair?

**Pull request merged**
